
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class showstudentdetails extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rst = null;
    ResultSet rst1 = null;
    ResultSet rst2 = null;
    ResultSet rst3 = null;
    ResultSet rst4 = null;
    ResultSet rst5 = null;
    ResultSet rst6 = null;
    ResultSet rst7 = null;
    ResultSet rst8 = null;
    ResultSet rst9 = null;
    ResultSet rst10 = null;
    Connection con = null;
    Statement pst = null;
    ResultSet rs = null;
    
    public showstudentdetails() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table10 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        table6 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        table5 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        table7 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        table9 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        table8 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("STZhongsong", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Your Details");

        jButton1.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.setAlignmentX(1.0F);
        table.setAlignmentY(1.0F);
        table.setRowHeight(35);
        jScrollPane1.setViewportView(table);

        jButton2.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account.png"))); // NOI18N
        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Student ID ---");

        id.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Username ---");

        username.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Password  ---");

        password.setFont(new java.awt.Font("STZhongsong", 1, 18)); // NOI18N

        table10.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table10.setRowHeight(35);
        jScrollPane2.setViewportView(table10);

        table1.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table1.setAlignmentX(1.0F);
        table1.setAlignmentY(1.0F);
        table1.setRowHeight(35);
        jScrollPane3.setViewportView(table1);

        table2.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table2.setAlignmentX(1.0F);
        table2.setAlignmentY(1.0F);
        table2.setRowHeight(35);
        jScrollPane4.setViewportView(table2);

        table6.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table6.setAlignmentX(1.0F);
        table6.setAlignmentY(1.0F);
        table6.setRowHeight(35);
        jScrollPane5.setViewportView(table6);

        table5.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table5.setAlignmentX(1.0F);
        table5.setAlignmentY(1.0F);
        table5.setRowHeight(35);
        jScrollPane6.setViewportView(table5);

        table4.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table4.setAlignmentX(1.0F);
        table4.setAlignmentY(1.0F);
        table4.setRowHeight(35);
        jScrollPane7.setViewportView(table4);

        table3.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table3.setAlignmentX(1.0F);
        table3.setAlignmentY(1.0F);
        table3.setRowHeight(35);
        jScrollPane8.setViewportView(table3);

        table7.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table7.setAlignmentX(1.0F);
        table7.setAlignmentY(1.0F);
        table7.setRowHeight(35);
        jScrollPane9.setViewportView(table7);

        table9.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table9.setAlignmentX(1.0F);
        table9.setAlignmentY(1.0F);
        table9.setRowHeight(35);
        jScrollPane10.setViewportView(table9);

        table8.setFont(new java.awt.Font("STZhongsong", 1, 24)); // NOI18N
        table8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table8.setAlignmentX(1.0F);
        table8.setAlignmentY(1.0F);
        table8.setRowHeight(35);
        jScrollPane11.setViewportView(table8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(265, 265, 265)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(password))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(username)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1124, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String id1 = id.getText();
        String user = username.getText();
        String pass = String.valueOf(password.getText());
        try{
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/elearn", "root", "");//Establishing connection
            System.out.println("Connected With the database successfully");
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            String sql = "SELECT * FROM Student WHERE Username = '"+user+"' and Password = '"+pass+"' and ID = '"+id1+"';";
            pst = con.createStatement();
            pst.execute(sql);
            rs = pst.executeQuery(sql);
            
            
        if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Login Successfull", "Login Success", 1);
                    
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/elearn", "root", "");//Establishing connection
                    System.out.println("Connected With the database successfully");
                    Statement st;
                    st = conn.createStatement();
                    String sqll;
                    sqll = "SELECT ID FROM Student WHERE ID= '"+id1+"';";
                    rst = st.executeQuery(sqll);
                    table.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table.setModel(DbUtils.resultSetToTableModel(rst));
                    
                    Statement st1;
                    st1 = conn.createStatement();
                    String sqll1;
                    sqll1 = "SELECT Name FROM Student WHERE ID= '"+id1+"';";
                    rst1 = st1.executeQuery(sqll1);
                    table1.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table1.setModel(DbUtils.resultSetToTableModel(rst1));
                    
                    Statement st2;
                    st2 = conn.createStatement();
                    String sqll2;
                    sqll2 = "SELECT Telephone FROM Student WHERE ID= '"+id1+"';";
                    rst2 = st2.executeQuery(sqll2);
                    table2.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table2.setModel(DbUtils.resultSetToTableModel(rst2));
                    
                    Statement st3;
                    st3 = conn.createStatement();
                    String sqll3;
                    sqll3 = "SELECT Grade FROM Student WHERE ID= '"+id1+"';";
                    rst3 = st3.executeQuery(sqll3);
                    table3.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table3.setModel(DbUtils.resultSetToTableModel(rst3));
                    
                    Statement st4;
                    st4 = conn.createStatement();
                    String sqll4;
                    sqll4 = "SELECT Class FROM Student WHERE ID= '"+id1+"';";
                    rst4 = st4.executeQuery(sqll4);
                    table4.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table4.setModel(DbUtils.resultSetToTableModel(rst4));
                    
                    Statement st5;
                    st5 = conn.createStatement();
                    String sqll5;
                    sqll5 = "SELECT Guardian FROM Student WHERE ID= '"+id1+"';";
                    rst5 = st5.executeQuery(sqll5);
                    table5.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table5.setModel(DbUtils.resultSetToTableModel(rst5));
                    
                    Statement st6;
                    st6 = conn.createStatement();
                    String sqll6;
                    sqll6 = "SELECT Gender FROM Student WHERE ID= '"+id1+"';";
                    rst6 = st6.executeQuery(sqll6);
                    table6.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table6.setModel(DbUtils.resultSetToTableModel(rst6));
                    
                    Statement st7;
                    st7 = conn.createStatement();
                    String sqll7;
                    sqll7 = "SELECT BirthDate FROM Student WHERE ID= '"+id1+"';";
                    rst7 = st7.executeQuery(sqll7);
                    table7.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table7.setModel(DbUtils.resultSetToTableModel(rst7));
                    
                    Statement st8;
                    st8 = conn.createStatement();
                    String sqll8;
                    sqll8 = "SELECT BirthMonth FROM Student WHERE ID= '"+id1+"';";
                    rst8 = st8.executeQuery(sqll8);
                    table8.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table8.setModel(DbUtils.resultSetToTableModel(rst8));
                    
                    Statement st9;
                    st9 = conn.createStatement();
                    String sqll9;
                    sqll9 = "SELECT BirthYear FROM Student WHERE ID= '"+id1+"';";
                    rst9 = st9.executeQuery(sqll9);
                    table9.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table9.setModel(DbUtils.resultSetToTableModel(rst9));
                    
                    Statement st10;
                    st10 = conn.createStatement();
                    String sqll10;
                    sqll10 = "SELECT Address FROM Student WHERE ID= '"+id1+"';";
                    rst10 = st10.executeQuery(sqll10);
                    table10.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 22));
                    table10.setModel(DbUtils.resultSetToTableModel(rst10));
            }
            else{
                    JOptionPane.showMessageDialog(null, "Incorrect ID or Username Or Password", "Login Failed", 2);
                }
            
        }catch(SQLException e){
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(showstudentdetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(showstudentdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        student page = new student();
        page.setVisible(true);
        
        new showstudentdetails().setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showstudentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showstudentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showstudentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showstudentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new showstudentdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPasswordField password;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTable table10;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTable table4;
    private javax.swing.JTable table5;
    private javax.swing.JTable table6;
    private javax.swing.JTable table7;
    private javax.swing.JTable table8;
    private javax.swing.JTable table9;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
